export const CONVERSATION_CREATE_REQUEST = "CONVERSATION_CREATE_REQUEST";
export const CONVERSATION_CREATE_SUCCESS = "CONVERSATION_CREATE_SUCCESS";
export const CONVERSATION_CREATE_FAIL = "CONVERSATION_CREATE_FAIL";
export const CONVERSATION_CREATE_RESET = "CONVERSATION_CREATE_RESET";

export const CONVERSATION_LIST_REQUEST = "CONVERSATION_LIST_REQUEST";
export const CONVERSATION_LIST_SUCCESS = "CONVERSATION_LIST_SUCCESS";
export const CONVERSATION_LIST_FAIL = "CONVERSATION_LIST_FAIL";
export const CONVERSATION_LIST_RESET = "CONVERSATION_LIST_RESET";
