export const POST_CREATE_REQUEST = "POST_CREATE_REQUEST";
export const POST_CREATE_SUCCESS = "POST_CREATE_SUCCESS";
export const POST_CREATE_FAIL = "POST_CREATE_FAIL";
export const POST_CREATE_RESET = "POST_CREATE_RESET";

export const POST_LIST_REQUEST = "POST_LIST_REQUEST";
export const POST_LIST_SUCCESS = "POST_LIST_SUCCESS";
export const POST_LIST_FAIL = "POST_LIST_FAIL";
export const POST_LIST_RESET = "POST_LIST_RESET";

export const POST_LIST_CREATED_REQUEST = "POST_LIST_CREATED_REQUEST";
export const POST_LIST_CREATED_SUCCESS = "POST_LIST_CREATED_SUCCESS";
export const POST_LIST_CREATED_FAIL = "POST_LIST_CREATED_FAIL";
export const POST_LIST_CREATED_RESET = "POST_LIST_CREATED_RESET";

export const POST_TOGGLE_LIKE_REQUEST = "POST_TOGGLE_LIKE_REQUEST";
export const POST_TOGGLE_LIKE_SUCCESS = "POST_TOGGLE_LIKE_SUCCESS";
export const POST_TOGGLE_LIKE_FAIL = "POST_TOGGLE_LIKE_FAIL";
