export const USER_LOGOUT = "USER_LOGOUT";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_LOGIN_WITH_FB_REQUEST = "USER_LOGIN_WITH_FB_REQUEST";
export const USER_LOGIN_WITH_FB_SUCCESS = "USER_LOGIN_WITH_FB_SUCCESS";
export const USER_LOGIN_WITH_FB_FAIL = "USER_LOGIN_WITH_FB_FAIL";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_SUGGESTED_REQUEST = "USER_SUGGESTED_REQUEST";
export const USER_SUGGESTED_SUCCESS = "USER_SUGGESTED_SUCCESS";
export const USER_SUGGESTED_FAIL = "USER_SUGGESTED_FAIL";
export const USER_SUGGESTED_RESET = "USER_SUGGESTED_RESET";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";
export const USER_DETAILS_RESET = "USER_DETAILS_RESET";

export const USER_FOLLOW_REQUEST = "USER_FOLLOW_REQUEST";
export const USER_FOLLOW_SUCCESS = "USER_FOLLOW_SUCCESS";
export const USER_FOLLOW_FAIL = "USER_FOLLOW_FAIL";

export const USER_COMMENT_REQUEST = "USER_COMMENT_REQUEST";
export const USER_COMMENT_SUCCESS = "USER_COMMENT_SUCCESS";
export const USER_COMMENT_FAIL = "USER_COMMENT_FAIL";

export const USER_UPDATE_AVATAR_REQUEST = "USER_UPDATE_AVATAR_REQUEST";
export const USER_UPDATE_AVATAR_SUCCESS = "USER_UPDATE_AVATAR_SUCCESS";
export const USER_UPDATE_AVATAR_FAIL = "USER_UPDATE_AVATAR_FAIL";
export const USER_UPDATE_AVATAR_RESET = "USER_UPDATE_AVATAR_RESET";

export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL";
export const USER_UPDATE_RESET = "USER_UPDATE_RESET";

export const USER_UPDATE_PASSWORD_REQUEST = "USER_UPDATE_PASSWORD_REQUEST";
export const USER_UPDATE_PASSWORD_SUCCESS = "USER_UPDATE_PASSWORD_SUCCESS";
export const USER_UPDATE_PASSWORD_FAIL = "USER_UPDATE_PASSWORD_FAIL";

export const USER_DELETE_AVATAR_REQUEST = "USER_DELETE_AVATAR_REQUEST";
export const USER_DELETE_AVATAR_SUCCESS = "USER_DELETE_AVATAR_SUCCESS";
export const USER_DELETE_AVATAR_FAIL = "USER_DELETE_AVATAR_FAIL";
export const USER_DELETE_AVATAR_RESET = "USER_DELETE_AVATAR_RESET";

export const USER_FIND_REQUEST = "USER_FIND_REQUEST";
export const USER_FIND_SUCCESS = "USER_FIND_SUCCESS";
export const USER_FIND_FAIL = "USER_FIND_FAIL";
